---
language: ruby
before_install:
  - gem install bundler
  - bundle install
  - docker pull alpine:latest
  - pip install bashate
matrix:
  fast_finish: true
  include:
  - rvm: '2.1'
    sudo: required
    services: docker
    script:
      - bashate -i E003,E006 entrypoint.sh
      - bundle exec rspec spec/