# action.yml
name: 'Image Resizer Inplace'
description: 'In place resize images inside a folder'
branding:
  icon: 'image'  
  color: 'green'
inputs:
  target:
    description: 'Folder in which images are stored'
    required: true
    default: 'images'
  dimensions:
    description: 'New resolution for images'
    required: true
    default: '500x'
outputs:
  time:
    description: 'The time we greeted you'
    
jobs:   
  resizing:
    name: Resize Operations
    runs-on: ubuntu-latest
    steps:
    - name: Install pre-requisites
      run: sudo apt-get install build-essential 
    - name: Install Imagemagick
      run: sudo apt-get install imagemagick
    - name: Get into the input folder
      run: |
        cd $INPUT_TARGET
    - name: apply conversion
      run: |
        mogrify -path . -auto-orient -thumbnail $INPUT_DIMENSIONS *.*
        
