# action.yml
name: 'Image Resizer Inplace'
description: 'In place resize images inside a folder'
branding:
  icon: 'image'  
  color: 'green'
inputs:
  target:
    description: 'Folder in which images are stored'
    required: true
    default: 'images'
  dimensions:
    description: 'New resolution for images'
    required: true
    default: '500x'
outputs:
  time:
    description: 'The time we greeted you'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
    - ${{ inputs.dimensions }}
